from . import test_tms_order
from . import test_tms_cargo
from . import test_tms_route
from . import test_res_partner
from . import test_tms_driver
from . import test_tms_team
from . import test_tms_crew
from . import test_fleet_vehicle
from . import test_tms_stage
from . import test_tms_convoy
from . import test_res_config_settings
