from . import res_config_settings
from . import tms_stage
from . import tms_insurance
from . import tms_driver
from . import res_partner
from . import tms_crew
from . import tms_order
from . import tms_route
from . import tms_team
from . import fleet_vehicle
