from . import toursolver_request_props_definition
from . import toursolver_backend
from . import res_company
from . import res_config_settings
from . import toursolver_resource
from . import toursolver_task
from . import stock_picking
from . import toursolver_delivery_window
from . import res_partner
from . import shipment_advice
