[project]
name = "odoo-addons-oca-stock-logistics-transport"
version = "19.0.20260708.2"
dependencies = [
    "odoo-addon-tms==19.0.*",
    "odoo-addon-tms_account==19.0.*",
    "odoo-addon-tms_expense==19.0.*",
    "odoo-addon-tms_product==19.0.*",
    "odoo-addon-tms_purchase==19.0.*",
    "odoo-addon-tms_sale==19.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 19.0",
]
