[project]
name = "odoo-addons-oca-stock-logistics-transport"
version = "18.0.20241023.0"
dependencies = [
    "odoo-addon-tms==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
